apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  labels:
    app: loan-service
spec:
  replicas: 2
  selector:
    matchLabels:
      appname: loan-service
  template:
    metadata:
      name: loan-service
      labels:
        appname: loan-service
    spec:
      containers:
        - name: loan-service
          image: vinothg2309/loan-service
          envFrom:
            - configMapRef:
                name: micro-config-map
          ports:
            - containerPort: 8102
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loan-service
  labels:
    app: loan-svc
spec:
  type: LoadBalancer
  ports:
    - name: port1
      protocol: TCP
      port: 801
      targetPort: 8102
  selector:
    appname: loan-service
