apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-inx-dev
  namespace: dev
  labels:
    name: nginx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod-dev
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod-dev
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev
  labels:
    app: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-pod-dev
  ports:
    - name: service-port
      port: 8001
      targetPort: 8000
      nodePort: 30000



